<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Acme.Center.Platform</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
        <PackageReference Include="Humanizer" Version="3.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.18.0" />
        <PackageReference Include="MySql.EntityFrameworkCore" Version="8.0.11" />
        <PackageReference Include="MySqlConnector" Version="2.3.7" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.2.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    </ItemGroup>

</Project>
