// <auto-generated />
using System;
using Acme.Center.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acme.Center.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Acme.Center.Platform.Hazards.Domain.Model.Aggregates.Hazard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("BaseRiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("base_risk_level");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hazards");

                    b.ToTable("hazards");
                });

            modelBuilder.Entity("Acme.Center.Platform.Iam.Domain.Model.Aggregates.AccessLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AttemptAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("attempt_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext")
                        .HasColumnName("user_id");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("was_successful");

                    b.HasKey("Id")
                        .HasName("pk_access_logs");

                    b.ToTable("access_logs");
                });

            modelBuilder.Entity("Acme.Center.Platform.Iam.Domain.Model.Aggregates.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Acme.Center.Platform.Iam.Domain.Model.Aggregates.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("CloseReason")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("close_reason");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_valid");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("TokenSignature")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token_signature");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("Acme.Center.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("account_status");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role_id");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int")
                        .HasColumnName("sector_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Acme.Center.Platform.Inspections.Domain.Model.Aggregates.Danger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_dangers");

                    b.ToTable("dangers");
                });

            modelBuilder.Entity("Acme.Center.Platform.Inspections.Domain.Model.Aggregates.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("CorrectiveAction")
                        .HasColumnType("longtext")
                        .HasColumnName("corrective_action");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("HeadquartersId")
                        .HasColumnType("int")
                        .HasColumnName("headquarters_id");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("incident_type");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("operator_id");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("photo_url");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("report_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ticket");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_date");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("urgency_level");

                    b.HasKey("Id")
                        .HasName("pk_inspections");

                    b.HasIndex("Ticket")
                        .IsUnique()
                        .HasDatabaseName("ix_inspections_ticket");

                    b.ToTable("inspections");
                });

            modelBuilder.Entity("Acme.Center.Platform.Inspections.Domain.Model.Aggregates.PhotoEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_url");

                    b.Property<int>("InspectionId")
                        .HasColumnType("int")
                        .HasColumnName("inspection_id");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("upload_date");

                    b.HasKey("Id")
                        .HasName("pk_photo_evidences");

                    b.ToTable("photo_evidences");
                });

            modelBuilder.Entity("Acme.Center.Platform.Mitigations.Domain.Model.Aggregates.CorrectiveActionTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTechnicianId")
                        .HasColumnType("longtext")
                        .HasColumnName("assigned_technician_id");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("closure_date");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("CriticalityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("criticality_level");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("instructions");

                    b.Property<string>("ReportId")
                        .HasColumnType("longtext")
                        .HasColumnName("report_id");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("risk_type");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sector");

                    b.Property<string>("SectorId")
                        .HasColumnType("longtext")
                        .HasColumnName("sector_id");

                    b.Property<int>("SlaLimitHours")
                        .HasColumnType("int")
                        .HasColumnName("sla_limit_hours");

                    b.Property<bool>("SlaMissed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sla_missed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("technician_name");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("int")
                        .HasColumnName("ticket_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_corrective_action_tickets");

                    b.ToTable("corrective_action_tickets");
                });

            modelBuilder.Entity("Acme.Center.Platform.Mitigations.Domain.Model.Aggregates.CriticalNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<bool>("Sent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sent");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_date");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("longtext")
                        .HasColumnName("supervisor_id");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("supervisor_name");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_critical_notifications");

                    b.ToTable("critical_notifications");
                });

            modelBuilder.Entity("Acme.Center.Platform.Mitigations.Domain.Model.Aggregates.MeasureVerification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("JustificationComment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("justification_comment");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("longtext")
                        .HasColumnName("supervisor_id");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("supervisor_name");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("verdict");

                    b.Property<DateTime>("VerificationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verification_date");

                    b.HasKey("Id")
                        .HasName("pk_measure_verifications");

                    b.ToTable("measure_verifications");
                });

            modelBuilder.Entity("Acme.Center.Platform.Mitigations.Domain.Model.Aggregates.Mitigation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("execution_date");

                    b.Property<string>("Observations")
                        .HasColumnType("longtext")
                        .HasColumnName("observations");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("responsible");

                    b.Property<string>("Result")
                        .HasColumnType("longtext")
                        .HasColumnName("result");

                    b.Property<string>("RiskAssessmentId")
                        .HasColumnType("longtext")
                        .HasColumnName("risk_assessment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TicketId")
                        .HasColumnType("longtext")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mitigations");

                    b.ToTable("mitigations");
                });

            modelBuilder.Entity("Acme.Center.Platform.Mitigations.Domain.Model.Aggregates.SlaAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AlertDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("alert_date");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ElapsedHours")
                        .HasColumnType("int")
                        .HasColumnName("elapsed_hours");

                    b.Property<string>("NotifiedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("notified_name");

                    b.Property<string>("NotifiedTo")
                        .HasColumnType("longtext")
                        .HasColumnName("notified_to");

                    b.Property<int>("SlaLimitHours")
                        .HasColumnType("int")
                        .HasColumnName("sla_limit_hours");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sla_alerts");

                    b.ToTable("sla_alerts");
                });

            modelBuilder.Entity("Acme.Center.Platform.Mitigations.Domain.Model.Aggregates.TicketHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("details");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_ticket_histories");

                    b.ToTable("ticket_histories");
                });

            modelBuilder.Entity("Acme.Center.Platform.MonitoringDashboard.Domain.Model.Aggregates.ArchivedReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("archive_date");

                    b.Property<string>("HashIntegrity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hash_integrity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_archived_reports");

                    b.ToTable("archived_reports");
                });

            modelBuilder.Entity("Acme.Center.Platform.MonitoringDashboard.Domain.Model.Aggregates.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("SectorId")
                        .HasColumnType("int")
                        .HasColumnName("sector_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_assets");

                    b.ToTable("dashboard_assets");
                });

            modelBuilder.Entity("Acme.Center.Platform.MonitoringDashboard.Domain.Model.Aggregates.HeatMapZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("HeatIndex")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("heat_index");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("risk_level");

                    b.Property<int>("SectorId")
                        .HasColumnType("int")
                        .HasColumnName("sector_id");

                    b.HasKey("Id")
                        .HasName("pk_heat_map_zones");

                    b.ToTable("heat_map_zones");
                });

            modelBuilder.Entity("Acme.Center.Platform.MonitoringDashboard.Domain.Model.Aggregates.PreventiveMaintenance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("asset_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_preventive_maintenances");

                    b.ToTable("preventive_maintenances");
                });

            modelBuilder.Entity("Acme.Center.Platform.MonitoringDashboard.Domain.Model.Aggregates.Technician", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("specialty");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_technicians");

                    b.ToTable("dashboard_technicians");
                });

            modelBuilder.Entity("Acme.Center.Platform.MonitoringDashboard.Domain.Model.Aggregates.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTechnicianId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("assigned_technician_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("priority");

                    b.Property<int>("SectorId")
                        .HasColumnType("int")
                        .HasColumnName("sector_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_tickets");

                    b.ToTable("dashboard_tickets");
                });

            modelBuilder.Entity("Acme.Center.Platform.OrganizationAssets.Domain.Model.Aggregates.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("HeadquartersId")
                        .HasColumnType("int")
                        .HasColumnName("headquarters_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("risk_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_areas");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_areas_code");

                    b.ToTable("areas");
                });

            modelBuilder.Entity("Acme.Center.Platform.OrganizationAssets.Domain.Model.Aggregates.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcquisitionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("acquisition_date");

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deactivation_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("HeadquartersId")
                        .HasColumnType("int")
                        .HasColumnName("headquarters_id");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_maintenance_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("SystemEntryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("system_entry_date");

                    b.HasKey("Id")
                        .HasName("pk_org_assets");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_org_assets_code");

                    b.ToTable("org_assets");
                });

            modelBuilder.Entity("Acme.Center.Platform.OrganizationAssets.Domain.Model.Aggregates.Headquarters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_headquarters");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_headquarters_name");

                    b.ToTable("headquarters");
                });

            modelBuilder.Entity("Acme.Center.Platform.ReportsCompliance.Domain.Model.Aggregates.AnnualOhsPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<int>("CompletedActivities")
                        .HasColumnType("int")
                        .HasColumnName("completed_activities")
                        .HasAnnotation("Relational:JsonPropertyName", "completed_activities");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GlobalCompliance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("global_compliance")
                        .HasAnnotation("Relational:JsonPropertyName", "global_compliance");

                    b.Property<decimal>("Goal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("goal");

                    b.Property<int>("TotalActivities")
                        .HasColumnType("int")
                        .HasColumnName("total_activities")
                        .HasAnnotation("Relational:JsonPropertyName", "total_activities");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_annual_ohs_plans");

                    b.ToTable("annual_ohs_plans");
                });

            modelBuilder.Entity("Acme.Center.Platform.ReportsCompliance.Domain.Model.Aggregates.CriticalAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ElapsedHours")
                        .HasColumnType("int")
                        .HasColumnName("elapsed_hours")
                        .HasAnnotation("Relational:JsonPropertyName", "elapsed_hours");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("ResponsibleSupervisor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("responsible_supervisor")
                        .HasAnnotation("Relational:JsonPropertyName", "responsible_supervisor");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("risk_type")
                        .HasAnnotation("Relational:JsonPropertyName", "risk_type");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sector");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_critical_alerts");

                    b.ToTable("critical_alerts");
                });

            modelBuilder.Entity("Acme.Center.Platform.ReportsCompliance.Domain.Model.Aggregates.CumulativeStIndicator", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<decimal>("ComplianceRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("compliance_rate")
                        .HasAnnotation("Relational:JsonPropertyName", "compliance_rate");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("period");

                    b.Property<int>("ResolvedIncidents")
                        .HasColumnType("int")
                        .HasColumnName("resolved_incidents")
                        .HasAnnotation("Relational:JsonPropertyName", "resolved_incidents");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("int")
                        .HasColumnName("total_incidents")
                        .HasAnnotation("Relational:JsonPropertyName", "total_incidents");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cumulative_st_indicators");

                    b.ToTable("cumulative_st_indicators");
                });

            modelBuilder.Entity("Acme.Center.Platform.ReportsCompliance.Domain.Model.Aggregates.GeneratedReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date")
                        .HasAnnotation("Relational:JsonPropertyName", "end_date");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name")
                        .HasAnnotation("Relational:JsonPropertyName", "file_name");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("format");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generation_date")
                        .HasAnnotation("Relational:JsonPropertyName", "generation_date");

                    b.Property<int?>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<string>("SectorFilter")
                        .HasColumnType("longtext")
                        .HasColumnName("sector_filter")
                        .HasAnnotation("Relational:JsonPropertyName", "sector_filter");

                    b.Property<int?>("SizeKb")
                        .HasColumnType("int")
                        .HasColumnName("size_kb")
                        .HasAnnotation("Relational:JsonPropertyName", "size_kb");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date")
                        .HasAnnotation("Relational:JsonPropertyName", "start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_generated_reports");

                    b.ToTable("generated_reports");
                });

            modelBuilder.Entity("Acme.Center.Platform.ReportsCompliance.Domain.Model.Aggregates.HistoricalIncidentRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("closing_date");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("criticality");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("incident_type");

                    b.Property<string>("OperatorId")
                        .HasColumnType("longtext")
                        .HasColumnName("operator_id");

                    b.Property<int?>("ResolutionTimeHours")
                        .HasColumnType("int")
                        .HasColumnName("resolution_time_hours");

                    b.Property<bool>("Resolved")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("resolved");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sector");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_historical_incident_records");

                    b.ToTable("historical_incident_records");
                });

            modelBuilder.Entity("Acme.Center.Platform.ReportsCompliance.Domain.Model.Aggregates.HistoricalTrend", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sector");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("int")
                        .HasColumnName("total_incidents")
                        .HasAnnotation("Relational:JsonPropertyName", "total_incidents");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_historical_trends");

                    b.ToTable("historical_trends");
                });

            modelBuilder.Entity("Acme.Center.Platform.ReportsCompliance.Domain.Model.Aggregates.KpiDashboard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Goal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_date")
                        .HasAnnotation("Relational:JsonPropertyName", "update_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_kpi_dashboards");

                    b.ToTable("kpi_dashboards");
                });

            modelBuilder.Entity("Acme.Center.Platform.ReportsCompliance.Domain.Model.Aggregates.MonthlyReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<decimal>("CompliancePercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("compliance_percentage")
                        .HasAnnotation("Relational:JsonPropertyName", "compliance_percentage");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "generated_at");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<int>("ResolvedIncidents")
                        .HasColumnType("int")
                        .HasColumnName("resolved_incidents")
                        .HasAnnotation("Relational:JsonPropertyName", "resolved_incidents");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("int")
                        .HasColumnName("total_incidents")
                        .HasAnnotation("Relational:JsonPropertyName", "total_incidents");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_monthly_reports");

                    b.ToTable("monthly_reports");
                });

            modelBuilder.Entity("Acme.Center.Platform.ReportsCompliance.Domain.Model.Aggregates.PredictiveIndicator", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trend");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_predictive_indicators");

                    b.ToTable("predictive_indicators");
                });

            modelBuilder.Entity("Acme.Center.Platform.RiskAssessments.Domain.Model.Aggregates.AreaCriticalityLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CriticalityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("criticality_level");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<string>("MapIntensity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("map_intensity");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sector");

                    b.Property<string>("SectorId")
                        .HasColumnType("longtext")
                        .HasColumnName("sector_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_area_criticality_levels");

                    b.ToTable("area_criticality_levels");
                });

            modelBuilder.Entity("Acme.Center.Platform.RiskAssessments.Domain.Model.Aggregates.DailySummary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sector");

                    b.Property<string>("SectorId")
                        .HasColumnType("longtext")
                        .HasColumnName("sector_id");

                    b.Property<int>("TotalInProgress")
                        .HasColumnType("int")
                        .HasColumnName("total_in_progress");

                    b.Property<int>("TotalNew")
                        .HasColumnType("int")
                        .HasColumnName("total_new");

                    b.Property<int>("TotalResolved")
                        .HasColumnType("int")
                        .HasColumnName("total_resolved");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_daily_summaries");

                    b.ToTable("daily_summaries");
                });

            modelBuilder.Entity("Acme.Center.Platform.RiskAssessments.Domain.Model.Aggregates.PatternAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FirstReportDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_report_date");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generation_date");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("int")
                        .HasColumnName("occurrence_count");

                    b.Property<string>("PatternId")
                        .HasColumnType("longtext")
                        .HasColumnName("pattern_id");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("risk_type");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sector");

                    b.Property<string>("SectorId")
                        .HasColumnType("longtext")
                        .HasColumnName("sector_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pattern_alerts");

                    b.ToTable("pattern_alerts");
                });

            modelBuilder.Entity("Acme.Center.Platform.RiskAssessments.Domain.Model.Aggregates.RiskAssessment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("ControlMeasures")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("control_measures");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("evaluation_date");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("hazard_type");

                    b.Property<int>("Probability")
                        .HasColumnType("int")
                        .HasColumnName("probability");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("risk_level");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sector");

                    b.Property<int>("Severity")
                        .HasColumnType("int")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_risk_assessments");

                    b.ToTable("risk_assessments");
                });

            modelBuilder.Entity("Acme.Center.Platform.RiskAssessments.Domain.Model.Aggregates.RiskPattern", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<int>("AnalysisPeriodDays")
                        .HasColumnType("int")
                        .HasColumnName("analysis_period_days");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FirstOccurrenceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_occurrence_date");

                    b.Property<int>("Frequency")
                        .HasColumnType("int")
                        .HasColumnName("frequency");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("hazard_type");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("incident_type");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_reviewed");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("review_date");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sector");

                    b.Property<string>("SectorId")
                        .HasColumnType("longtext")
                        .HasColumnName("sector_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_risk_patterns");

                    b.ToTable("risk_patterns");
                });

            modelBuilder.Entity("Acme.Center.Platform.Technicians.Domain.Model.Aggregates.Technician", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("document_number");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("specialty");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_technicians");

                    b.ToTable("technicians");
                });
#pragma warning restore 612, 618
        }
    }
}
